language: php
php:
  - '7.1'

services:
  - mysql


before_script:
  - cp ~/coral/common/configuration_sample.ini ~/coral/common/configuration.ini
  - cp ~/coral/auth/configuration_sample.ini ~/coral/auth/configuration.ini

before_install:
  - mysql -e 'CREATE DATABASE coral_auth_prod;'
