language: php
php:
  - '7.1'

services:
  - mysql


before_script:
  - cp common/configuration_sample.ini common/configuration.ini
  - cp auth/configuration_sample.ini auth/configuration.ini

before_install:
  - mysql -e 'CREATE DATABASE coral_auth_prod;'
